name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run python unit tests
        run: |
          python -m unittest -q tests/test_forbidden_templates.py

      - name: Set up Node (verify build deps)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm deps
        run: |
          if [ -f package.json ]; then npm ci; fi

  build-and-deploy:
    name: Build site and deploy (only after tests pass)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Hugo CLI
        env:
          HUGO_VERSION: '0.149.0'
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm deps
        run: npm ci

      - name: Build Tailwind CSS
        run: |
          npm run build:css

      - name: Build with Hugo
        env:
          HUGO_ENV: production
        run: |
          hugo --minify --gc --baseURL "${{ steps.pages.outputs.base_url }}//"

      - name: Ensure .nojekyll
        run: |
          touch public/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
